/**
 * World boundary generator: `npm run world` (one-shot; output committed).
 *
 * Decodes world-atlas countries-110m (Natural Earth Admin 0, public domain)
 * with topojson-client and emits content/data/world-lines.ts: the deduped
 * coastline + border mesh as plain [lon, lat] line strings, rounded to two
 * decimals. OpsGlobe imports the module into its already-lazy ssr:false
 * chunk and converts the strings to LineSegments on the sphere; no runtime
 * fetch, no CSP change, no async geometry.
 *
 * topojson.mesh emits every shared border exactly once, roughly halving the
 * vertex count versus per-country rings and eliminating double-bright
 * overlapping strokes.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import * as topojson from "topojson-client";

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const topologyPath = require.resolve("world-atlas/countries-110m.json");
const topology = JSON.parse(await readFile(topologyPath, "utf8"));
const mesh = topojson.mesh(topology, topology.objects.countries);

const round = (n) => Math.round(n * 100) / 100;
const lines = mesh.coordinates.map((line) => line.map(([lon, lat]) => [round(lon), round(lat)]));

const points = lines.reduce((acc, line) => acc + line.length, 0);
const body = lines
  .map((line) => `  [${line.map(([lon, lat]) => `${lon},${lat}`).join(",")}],`)
  .join("\n");

const source = `// GENERATED by scripts/build-world.mjs from world-atlas countries-110m
// (Natural Earth, public domain). Do not edit by hand; re-run \`npm run world\`.
//
// Deduped coastline + border mesh as flat [lon0, lat0, lon1, lat1, ...] line
// strings (two-decimal degrees). Consumed only by components/three/OpsGlobe
// inside the lazy ssr:false globe chunk.

export const WORLD_LINES: readonly (readonly number[])[] = [
${body}
] as const;
`;

const outPath = path.join(root, "content", "data", "world-lines.ts");
await writeFile(outPath, source, "utf8");
console.log(
  `[world] ${lines.length} line strings, ${points} points -> content/data/world-lines.ts (${(source.length / 1024).toFixed(0)} KB)`,
);
