/**
 * Build-time image pipeline (deploy-agnostic replacement for host image
 * optimization). Reads the explicit manifest in assets.config.mjs, emits
 * avif/webp width variants plus one fallback (jpg for photos, png for alpha
 * artwork) into public/images/<category>/, renders the app icons, and
 * generates the typed manifest content/assets.ts that components consume via
 * <Pic>. Certificate PDFs are handled upstream by scripts/build-certs.mjs,
 * whose page-1 raster masters flow through here as the `certs` category with
 * document-legibility quality (fine print smears at photo quality).
 *
 * The typed manifest is written FIRST (metadata probing is fast) so dependent
 * work can start while the slow encodes run.
 */
import { mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { SOURCE_ROOT, images } from "./assets.config.mjs";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outBase = path.join(root, "public", "images");

const fallbackFormatFor = (entry) => (entry.alpha ? "png" : "jpg");

async function probe(entry) {
  const srcPath = path.join(SOURCE_ROOT, entry.src);
  await stat(srcPath); // fail fast with a clear path if the manifest is stale
  const meta = await sharp(srcPath, { limitInputPixels: false }).metadata();
  const widths = entry.widths.filter((w) => w <= meta.width);
  if (widths.length === 0) widths.push(Math.min(...entry.widths, meta.width));
  const maxW = Math.max(...widths);
  const outHeight = Math.round((meta.height / meta.width) * maxW);
  return { ...entry, srcPath, widths, width: maxW, height: outHeight };
}

function manifestSource(entries) {
  const lines = entries.map((e) => {
    const formats = e.alpha ? `["webp", "png"]` : `["avif", "webp", "${fallbackFormatFor(e)}"]`;
    return `  "${e.slug}": { category: "${e.category}", width: ${e.width}, height: ${e.height}, widths: [${e.widths.join(", ")}], formats: ${formats} },`;
  });
  return `// GENERATED by scripts/build-assets.mjs. Do not edit by hand; edit
// scripts/assets.config.mjs and re-run \`npm run assets\`.

export interface ImageEntry {
  category: "brand" | "certs" | "clients" | "iso" | "photos";
  /** intrinsic size of the largest generated variant (CLS guard) */
  width: number;
  height: number;
  widths: readonly number[];
  formats: readonly string[];
}

export const IMAGES = {
${lines.join("\n")}
} as const satisfies Record<string, ImageEntry>;

export type ImageKey = keyof typeof IMAGES;

export function imageSrc(key: ImageKey, width?: number, format?: string): string {
  const entry = IMAGES[key];
  const w = width ?? Math.max(...entry.widths);
  const f = format ?? entry.formats[entry.formats.length - 1];
  return \`/images/\${entry.category}/\${key}-\${w}.\${f}\`;
}
`;
}

async function encodeEntry(entry) {
  const dir = path.join(outBase, entry.category);
  await mkdir(dir, { recursive: true });
  const image = sharp(entry.srcPath, { limitInputPixels: false });
  const fallback = fallbackFormatFor(entry);
  // document scans need legibility over weight: AVIF q55 smears fine print
  const q = entry.doc
    ? { avif: 70, webp: 88, jpeg: 88 }
    : { avif: 55, webp: 80, jpeg: 82 };

  for (const w of entry.widths) {
    const resized = image.clone().resize({ width: w, withoutEnlargement: true });
    if (!entry.alpha) {
      await resized
        .clone()
        .avif({ quality: q.avif })
        .toFile(path.join(dir, `${entry.slug}-${w}.avif`));
    }
    await resized
      .clone()
      .webp({ quality: q.webp })
      .toFile(path.join(dir, `${entry.slug}-${w}.webp`));
  }

  const maxW = Math.max(...entry.widths);
  const resizedMax = image.clone().resize({ width: maxW, withoutEnlargement: true });
  if (fallback === "png") {
    await resizedMax.png({ compressionLevel: 9 }).toFile(path.join(dir, `${entry.slug}-${maxW}.png`));
  } else {
    await resizedMax
      .flatten({ background: entry.doc ? "#ffffff" : "#081020" })
      .jpeg({ quality: q.jpeg, mozjpeg: true })
      .toFile(path.join(dir, `${entry.slug}-${maxW}.jpg`));
  }
}

async function buildIcons() {
  // apple-icon: the same S-in-sonar-ring composition as app/icon.svg (favicon
  // v2, client decision 2026-08-03), but full-bleed (iOS applies its own
  // corner mask; a pre-rounded tile would leave notches inside the platform
  // shape). Keep this in sync with app/icon.svg on any geometry change.
  const appleSvg =
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">' +
    '<rect width="64" height="64" fill="#081020"/>' +
    '<g stroke="#ffffff" stroke-width="3" opacity="0.62" fill="none">' +
    '<circle cx="32" cy="32" r="23"/>' +
    '<path d="M32 4v5M32 55v5M4 32h5M55 32h5"/>' +
    "</g>" +
    '<path d="M 39 25 A 7 7 0 1 0 32 32 A 7 7 0 1 1 25 39" fill="none" stroke="#ffffff" stroke-width="5.5"/>' +
    "</svg>";
  await sharp(Buffer.from(appleSvg), { density: 288 })
    .resize(180, 180)
    .png()
    .toFile(path.join(root, "app", "apple-icon.png"));
}

const started = Date.now();
console.log(`[assets] probing ${images.length} sources...`);
const entries = [];
for (const entry of images) {
  entries.push(await probe(entry));
}

await mkdir(path.join(root, "content"), { recursive: true });
await writeFile(path.join(root, "content", "assets.ts"), manifestSource(entries), "utf8");
console.log(`[assets] content/assets.ts written (${entries.length} keys)`);

let done = 0;
for (const entry of entries) {
  await encodeEntry(entry);
  done += 1;
  console.log(`[assets] ${done}/${entries.length} ${entry.slug}`);
}
await buildIcons();
console.log(`[assets] icons written; total ${(Date.now() - started) / 1000 | 0}s`);
