/**
 * Certificate document manifest for scripts/build-certs.mjs.
 *
 * Each entry produces up to two outputs:
 *  - public/certs/<slug>.pdf      (copied, or page-1-extracted when
 *                                  firstPageOnly is set; skipped when
 *                                  copy: false because the file is already
 *                                  committed under public/certs)
 *  - Derived/Cert Pages/<slug>.png (a ~2000px page-1 raster master under
 *                                  SOURCE_ROOT, consumed by the image
 *                                  pipeline as ImageKey `cert-<slug>`;
 *                                  skipped when raster: false)
 *
 * `fromRepo: true` resolves src against public/certs (legacy documents that
 * were hand-copied in earlier rounds); otherwise src resolves against
 * SOURCE_ROOT like every other manifest.
 */

const NEW_DIR = "SOLAS MODU Certifications & Licenses 2.0";
const ISO_DIR = "SOLAS MODU ISO Certifications";
const SOW_DIR = "Derived/Scope Docs";

export const certDocuments = [
  // ---- current class approvals (2.0 repository) ----
  { src: `${NEW_DIR}/ABS CERTIFICATE NDT-PG1-2025-28.pdf`, slug: "abs-ndt-firm-2025" },
  { src: `${NEW_DIR}/ABS CERTIFICATE-TM FIRM-PG1-2025-28.pdf`, slug: "abs-tm-firm-2025" },
  { src: `${NEW_DIR}/IRS ESP CERT-PG1.pdf`, slug: "irs-esp-firm-2026" },
  { src: `${NEW_DIR}/IRS NDT CERT AMENDED P1.pdf`, slug: "irs-ndt-firm-2025" },

  // ---- current ISO cycle (Royal Assessments, 2.0 repository) ----
  { src: `${NEW_DIR}/SOLAS MODU MARINE SERVICES QMS.pdf`, slug: "iso-9001-2025" },
  { src: `${NEW_DIR}/SOLAS MODU MARINE SERVICES EMS.pdf`, slug: "iso-14001-2025" },
  { src: `${NEW_DIR}/SOLAS MODU MARINE SERVICES OHSMS.pdf`, slug: "iso-45001-2025" },

  // ---- registrations: page 1 only, the annexure never ships ----
  {
    src: `${NEW_DIR}/SOLAS MODU Udyam Registration Certificate with Annexure.pdf`,
    slug: "udyam-registration",
    firstPageOnly: true,
  },

  // ---- flag state: page 1 only (client decision 2026-07-30); overwrites
  //      the committed 5-page file at the same URL ----
  {
    src: "skanreg-inspector-agreement.pdf",
    slug: "skanreg-inspector-agreement",
    fromRepo: true,
    firstPageOnly: true,
  },

  // ---- scope-of-work summaries (generated by scripts/build-docs.mjs) ----
  { src: `${SOW_DIR}/sow-ongc-vessels-piping.pdf`, slug: "sow-ongc-vessels-piping" },
  { src: `${SOW_DIR}/sow-ongc-drilling-rigs.pdf`, slug: "sow-ongc-drilling-rigs" },
  { src: `${SOW_DIR}/sow-ongc-cranes-mh.pdf`, slug: "sow-ongc-cranes-mh" },
  { src: `${SOW_DIR}/sow-ongc-lrut-pipelines.pdf`, slug: "sow-ongc-lrut-pipelines" },
  { src: `${SOW_DIR}/sow-ongc-uran.pdf`, slug: "sow-ongc-uran" },
  { src: `${SOW_DIR}/sow-ongc-neelam-lifeboats.pdf`, slug: "sow-ongc-neelam-lifeboats" },
  { src: `${SOW_DIR}/sow-iocl-lrut-tuticorin.pdf`, slug: "sow-iocl-lrut-tuticorin" },
  { src: `${SOW_DIR}/sow-jagson-flag-state.pdf`, slug: "sow-jagson-flag-state" },
  { src: `${SOW_DIR}/sow-pipavav-rig-ndt.pdf`, slug: "sow-pipavav-rig-ndt" },

  // ---- kept legacy PDF-only rows: rasterize so they gain the modal ----
  { src: "bv-lsa-approval.pdf", slug: "bv-lsa-approval", fromRepo: true, copy: false },
  { src: "bv-hull-thickness.pdf", slug: "bv-hull-thickness", fromRepo: true, copy: false },
  { src: "deep-sea-treasure-lifeboat.pdf", slug: "deep-sea-treasure-lifeboat", fromRepo: true, copy: false },
  { src: "zanzibar-flag-authorization.pdf", slug: "zanzibar-flag-authorization", fromRepo: true, copy: false },

  // ---- legacy ISO PDF copies (migrated from build-assets `documents`);
  //      their modal images already exist in the `iso` category ----
  {
    src: `${ISO_DIR}/ISO 9001-2015 Certificate_Quality Management_2022-2025.pdf`,
    slug: "iso-9001-2015-quality-management-2022-2025",
    raster: false,
  },
  {
    src: `${ISO_DIR}/ISO 14001-2015 Certificate_Environmental Management_2022-2025.pdf`,
    slug: "iso-14001-2015-environmental-management-2022-2025",
    raster: false,
  },
  {
    src: `${ISO_DIR}/ISO 45001-2018 Certificate_Occupational Health and Safety_2022-2025.pdf`,
    slug: "iso-45001-2018-occupational-health-safety-2022-2025",
    raster: false,
  },
];
