"use client";

import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent,
  type PointerEvent,
  type ReactNode,
  type RefObject,
} from "react";
import * as THREE from "three";
import { Canvas, useFrame } from "@react-three/fiber";
import { useMotionHold } from "@/components/providers/MotionHold";
import { WORLD_LINES } from "@/content/data/world-lines";
import type { GlobeStation } from "./CollaborationGlobe";

/**
 * Wireframe operations globe. Imports three/R3F directly, so it must only
 * ever be loaded through next/dynamic({ ssr: false }) (CollaborationGlobe
 * does this). The R3F frame loop is the single engine for every rotation:
 * drag velocity, damping, and idle spin all live inside useFrame.
 */

const DEG = Math.PI / 180;
const GLOBE_RADIUS = 1;
const MARKER_RADIUS = 1.005;
const GRID_STEP_DEG = 15;
const RING_SEGMENTS = 64;
const ARC_SAMPLES = 72;
const ARC_LIFT = 0.05;
/**
 * Minimum hub-to-station angle for a dashed route (radians, ~7.5deg ~830km).
 * The Indian project cluster (Uran, Mumbai High, Pipavav) sits on the hub's
 * doorstep; zero-length arc stubs there read as rendering glitches, so those
 * stations are markers only and routes are drawn to distant stations.
 */
const ARC_MIN_ANGLE = 0.13;
const ROT_PER_PX = 0.005;
const KEY_NUDGE = 0.014;
const TILT_LIMIT = 0.6;
const IDLE_SPIN = 0.08;
const IDLE_THRESHOLD = 0.0006;
const DAMPING = 3;
const DASH_SPEED = 0.12;
const MAX_DELTA = 0.05;
const INITIAL_ROT = { x: 0.25, y: 2.5 };
const ACCENT = "#1d5bd8";
const STEEL = "#78b0f0";

interface DragState {
  dragging: boolean;
  lastX: number;
  lastY: number;
  dx: number;
  dy: number;
  velX: number;
  velY: number;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function latLonToVec3(lat: number, lon: number, r: number): THREE.Vector3 {
  const phi = (90 - lat) * DEG;
  const theta = (lon + 180) * DEG;
  return new THREE.Vector3(
    -r * Math.sin(phi) * Math.cos(theta),
    r * Math.cos(phi),
    r * Math.sin(phi) * Math.sin(theta),
  );
}

/** Latitude rings (equator separate, drawn stronger) + meridians, as one merged segment list each. */
function buildGraticule(): { grid: THREE.BufferGeometry; equator: THREE.BufferGeometry } {
  const gridPositions: number[] = [];
  const equatorPositions: number[] = [];

  const pushRing = (target: number[], lat: number) => {
    for (let i = 0; i < RING_SEGMENTS; i++) {
      const lonA = (i / RING_SEGMENTS) * 360 - 180;
      const lonB = ((i + 1) / RING_SEGMENTS) * 360 - 180;
      const a = latLonToVec3(lat, lonA, GLOBE_RADIUS);
      const b = latLonToVec3(lat, lonB, GLOBE_RADIUS);
      target.push(a.x, a.y, a.z, b.x, b.y, b.z);
    }
  };

  for (let lat = -75; lat <= 75; lat += GRID_STEP_DEG) {
    if (lat === 0) continue;
    pushRing(gridPositions, lat);
  }
  pushRing(equatorPositions, 0);

  for (let lon = -180; lon < 180; lon += GRID_STEP_DEG) {
    for (let i = 0; i < RING_SEGMENTS; i++) {
      const latA = (i / RING_SEGMENTS) * 180 - 90;
      const latB = ((i + 1) / RING_SEGMENTS) * 180 - 90;
      const a = latLonToVec3(latA, lon, GLOBE_RADIUS);
      const b = latLonToVec3(latB, lon, GLOBE_RADIUS);
      gridPositions.push(a.x, a.y, a.z, b.x, b.y, b.z);
    }
  }

  const grid = new THREE.BufferGeometry();
  grid.setAttribute("position", new THREE.Float32BufferAttribute(gridPositions, 3));
  const equator = new THREE.BufferGeometry();
  equator.setAttribute("position", new THREE.Float32BufferAttribute(equatorPositions, 3));
  return { grid, equator };
}

/**
 * Real country outlines (round 5): the deduped Natural Earth coastline +
 * border mesh from content/data/world-lines.ts (generated by
 * `npm run world`), converted to one merged LineSegments geometry. Data
 * pairs are [lon, lat] (GeoJSON order), the REVERSE of latLonToVec3's
 * signature. One draw call for the whole world.
 */
function buildCountryLines(): THREE.BufferGeometry {
  // slight lift over the graticule radius so co-linear borders and meridians
  // never z-fight (same trick as MARKER_RADIUS for the station dots)
  const r = GLOBE_RADIUS * 1.002;
  const positions: number[] = [];
  const a = new THREE.Vector3();
  const b = new THREE.Vector3();
  for (const line of WORLD_LINES) {
    for (let i = 0; i + 3 < line.length; i += 2) {
      a.copy(latLonToVec3(line[i + 1], line[i], r));
      b.copy(latLonToVec3(line[i + 3], line[i + 2], r));
      positions.push(a.x, a.y, a.z, b.x, b.y, b.z);
    }
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
  return geometry;
}

/** Great-circle arc between two stations with a slight radial lift and a cumulative-length attribute for the dash shader. */
function buildArcGeometry(from: THREE.Vector3, to: THREE.Vector3): THREE.BufferGeometry {
  const va = from.clone().normalize();
  const vb = to.clone().normalize();
  const angle = va.angleTo(vb);
  const sinAngle = Math.sin(angle);

  const positions = new Float32Array((ARC_SAMPLES + 1) * 3);
  const distances = new Float32Array(ARC_SAMPLES + 1);
  const prev = new THREE.Vector3();
  const cur = new THREE.Vector3();
  let acc = 0;

  for (let i = 0; i <= ARC_SAMPLES; i++) {
    const t = i / ARC_SAMPLES;
    if (sinAngle < 1e-6) {
      cur.copy(va);
    } else {
      const wa = Math.sin((1 - t) * angle) / sinAngle;
      const wb = Math.sin(t * angle) / sinAngle;
      cur.set(
        va.x * wa + vb.x * wb,
        va.y * wa + vb.y * wb,
        va.z * wa + vb.z * wb,
      );
    }
    cur.normalize().multiplyScalar(GLOBE_RADIUS * (1 + ARC_LIFT * Math.sin(t * Math.PI)));
    if (i > 0) acc += cur.distanceTo(prev);
    distances[i] = acc;
    positions[i * 3] = cur.x;
    positions[i * 3 + 1] = cur.y;
    positions[i * 3 + 2] = cur.z;
    prev.copy(cur);
  }

  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.BufferAttribute(positions, 3));
  geometry.setAttribute("aDist", new THREE.BufferAttribute(distances, 1));
  return geometry;
}

/** LineDashedMaterial has no dash offset, so the flow animation is a tiny shader over the cumulative-length attribute. */
function createDashMaterial(): THREE.ShaderMaterial {
  return new THREE.ShaderMaterial({
    transparent: true,
    depthWrite: false,
    uniforms: {
      uDashOffset: { value: 0 },
      uDash: { value: 0.045 },
      uPeriod: { value: 0.1 },
      uColor: { value: new THREE.Color(ACCENT) },
    },
    vertexShader: /* glsl */ `
      attribute float aDist;
      varying float vDist;
      void main() {
        vDist = aDist;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }
    `,
    fragmentShader: /* glsl */ `
      uniform float uDashOffset;
      uniform float uDash;
      uniform float uPeriod;
      uniform vec3 uColor;
      varying float vDist;
      void main() {
        float m = mod(vDist - uDashOffset, uPeriod);
        if (m > uDash) discard;
        gl_FragColor = vec4(uColor, 0.8);
      }
    `,
  });
}

interface GlobeSceneProps {
  stations: readonly GlobeStation[];
  dragRef: RefObject<DragState>;
  paused: boolean;
}

function GlobeScene({ stations, dragRef, paused }: GlobeSceneProps) {
  const groupRef = useRef<THREE.Group>(null);
  const rotRef = useRef({ ...INITIAL_ROT });

  const graticule = useMemo(() => buildGraticule(), []);
  const countries = useMemo(() => buildCountryLines(), []);
  const materials = useMemo(
    () => ({
      // grid dimmed slightly since round 5 so the land layer reads on top
      grid: new THREE.LineBasicMaterial({ color: STEEL, transparent: true, opacity: 0.1 }),
      equator: new THREE.LineBasicMaterial({ color: STEEL, transparent: true, opacity: 0.2 }),
      countries: new THREE.LineBasicMaterial({ color: STEEL, transparent: true, opacity: 0.38 }),
      marker: new THREE.MeshBasicMaterial({ color: ACCENT }),
      dash: createDashMaterial(),
    }),
    [],
  );
  const markerGeometry = useMemo(() => new THREE.SphereGeometry(0.018, 12, 12), []);
  const markerPositions = useMemo(
    () => stations.map((s) => latLonToVec3(s.lat, s.lon, MARKER_RADIUS)),
    [stations],
  );
  /** THREE.Line via <primitive>: the R3F <line> intrinsic is reserved for SVG. */
  const arcs = useMemo(() => {
    const hub = stations[0];
    if (!hub) return [];
    const hubVec = latLonToVec3(hub.lat, hub.lon, GLOBE_RADIUS);
    return stations
      .slice(1)
      .filter((s) => {
        const v = latLonToVec3(s.lat, s.lon, GLOBE_RADIUS);
        return hubVec.angleTo(v) >= ARC_MIN_ANGLE;
      })
      .map((s) => {
        const geometry = buildArcGeometry(hubVec, latLonToVec3(s.lat, s.lon, GLOBE_RADIUS));
        return new THREE.Line(geometry, materials.dash);
      });
  }, [stations, materials]);

  useEffect(() => {
    return () => {
      graticule.grid.dispose();
      graticule.equator.dispose();
      countries.dispose();
      markerGeometry.dispose();
      arcs.forEach((line) => line.geometry.dispose());
      materials.grid.dispose();
      materials.equator.dispose();
      materials.countries.dispose();
      materials.marker.dispose();
      materials.dash.dispose();
    };
  }, [graticule, countries, markerGeometry, arcs, materials]);

  useFrame((_, delta) => {
    if (paused) return;
    const d = Math.min(delta, MAX_DELTA);
    materials.dash.uniforms.uDashOffset.value += d * DASH_SPEED;

    const drag = dragRef.current;
    const rot = rotRef.current;
    if (drag.dragging) {
      const stepX = drag.dx * ROT_PER_PX;
      const stepY = drag.dy * ROT_PER_PX;
      rot.y += stepX;
      rot.x = clamp(rot.x + stepY, -TILT_LIMIT, TILT_LIMIT);
      drag.velX = stepX;
      drag.velY = stepY;
      drag.dx = 0;
      drag.dy = 0;
    } else {
      rot.y += drag.velX;
      rot.x = clamp(rot.x + drag.velY, -TILT_LIMIT, TILT_LIMIT);
      const damp = Math.exp(-d * DAMPING);
      drag.velX *= damp;
      drag.velY *= damp;
      if (Math.abs(drag.velX) < IDLE_THRESHOLD) rot.y += d * IDLE_SPIN;
    }
    groupRef.current?.rotation.set(rot.x, rot.y, 0);
  });

  return (
    <group ref={groupRef} rotation={[INITIAL_ROT.x, INITIAL_ROT.y, 0]}>
      <lineSegments geometry={graticule.grid} material={materials.grid} />
      <lineSegments geometry={graticule.equator} material={materials.equator} />
      <lineSegments geometry={countries} material={materials.countries} />
      {stations.map((station, i) => (
        <mesh
          key={station.id}
          geometry={markerGeometry}
          material={materials.marker}
          position={markerPositions[i]}
          scale={i === 0 ? 1.5 : station.minor ? 0.75 : 1}
        />
      ))}
      {arcs.map((line, i) => (
        <primitive key={i} object={line} />
      ))}
    </group>
  );
}

interface OpsGlobeProps {
  stations: readonly GlobeStation[];
  /** accessible description for the canvas wrapper */
  label: string;
  /** rendered by R3F when a WebGL context cannot be created */
  fallback?: ReactNode;
}

export function OpsGlobe({ stations, label, fallback }: OpsGlobeProps) {
  const { held } = useMotionHold();
  const [docHidden, setDocHidden] = useState(false);
  const [inView, setInView] = useState(false);
  const wrapRef = useRef<HTMLDivElement>(null);
  const dragRef = useRef<DragState>({
    dragging: false,
    lastX: 0,
    lastY: 0,
    dx: 0,
    dy: 0,
    velX: 0,
    velY: 0,
  });

  useEffect(() => {
    const update = () => setDocHidden(document.hidden);
    update();
    document.addEventListener("visibilitychange", update);
    return () => document.removeEventListener("visibilitychange", update);
  }, []);

  // frameloop flips to "never" whenever the globe leaves the viewport
  useEffect(() => {
    const el = wrapRef.current;
    if (!el || typeof IntersectionObserver === "undefined") {
      setInView(true);
      return;
    }
    const io = new IntersectionObserver(
      ([entry]) => setInView(entry.isIntersecting),
      { rootMargin: "120px" },
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  const active = inView && !held && !docHidden;

  const onPointerDown = (e: PointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    drag.dragging = true;
    drag.lastX = e.clientX;
    drag.lastY = e.clientY;
    drag.dx = 0;
    drag.dy = 0;
    e.currentTarget.setPointerCapture(e.pointerId);
  };

  const onPointerMove = (e: PointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    if (!drag.dragging) return;
    drag.dx += e.clientX - drag.lastX;
    drag.dy += e.clientY - drag.lastY;
    drag.lastX = e.clientX;
    drag.lastY = e.clientY;
  };

  const endDrag = () => {
    dragRef.current.dragging = false;
  };

  const onKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    switch (e.key) {
      case "ArrowLeft":
        drag.velX -= KEY_NUDGE;
        break;
      case "ArrowRight":
        drag.velX += KEY_NUDGE;
        break;
      case "ArrowUp":
        drag.velY -= KEY_NUDGE;
        break;
      case "ArrowDown":
        drag.velY += KEY_NUDGE;
        break;
      default:
        return;
    }
    e.preventDefault();
  };

  return (
    <div
      ref={wrapRef}
      role="img"
      aria-label={label}
      tabIndex={0}
      className="h-full w-full cursor-grab touch-pan-y outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent active:cursor-grabbing"
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={endDrag}
      onPointerCancel={endDrag}
      onLostPointerCapture={endDrag}
      onKeyDown={onKeyDown}
    >
      <Canvas
        dpr={[1, 1.5]}
        gl={{ antialias: false, powerPreference: "low-power", alpha: true }}
        camera={{ position: [0, 0, 3.1], fov: 45, near: 0.1, far: 10 }}
        frameloop={active ? "always" : "never"}
        fallback={fallback ?? null}
      >
        <GlobeScene stations={stations} dragRef={dragRef} paused={!active} />
      </Canvas>
    </div>
  );
}
